version: "3.5"
services:
  atcoer_env:
    container_name: Atcoder
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: "28gb"
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
    working_dir: /workspace
    ports:
      - "8080:8080"
    tty: true
