[tool.poetry]
name = "atcoder"
version = "0.1.0"
description = ""
authors = ["ryomac"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.2"
scipy = "^1.11.4"
networkx = "^3.2.1"
scikit-learn = "^1.3.2"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
